version: '3'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql/data
    ports:
      - 5432:5432

    environment:
      - MYSQL_DB=testDB
      - MYSQL_USER=postgres
      - MYSQL_PASSWORD=postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080